# Generated by Django 5.2.17 on 2026-10-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_orderitem_gift_wrap"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="attributes_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                verbose_name="اسنپ\u200cشاتِ ویژگی\u200cهای کالا",
            ),
        ),
    ]
