# Generated by Django 5.2.17 on 2026-10-02 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_cartitem_gift_message_cartitem_gift_wrap_option_code_and_more"),
        ("customers", "0004_customer_accepts_promotional_email_and_more"),
        ("orders", "0011_orderitem_attributes_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="gift_wrap_discount",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="تخفیفِ اعمال\u200cشده روی کادوپیچی",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="gift_wrap_scope",
            field=models.CharField(
                blank=True,
                default="",
                max_length=10,
                verbose_name="مبنای محاسبه\u200cی کادوپیچی (اسنپ\u200cشات)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="gift_wrap_total",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="هزینه\u200cی کادوپیچی",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="gift_message",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="پیامِ کارت\u200cهدیه",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="gift_wrap_option_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=30,
                verbose_name="گزینه\u200cی کادوپیچی (اسنپ\u200cشات)",
            ),
        ),
        migrations.CreateModel(
            name="CouponRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "رزروشده"),
                            ("redeemed", "مصرف\u200cشده"),
                            ("released", "آزادشده"),
                            ("refunded", "مستردشده"),
                        ],
                        db_index=True,
                        default="reserved",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="مبلغِ تخفیف",
                    ),
                ),
                (
                    "redeemed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ مصرف"
                    ),
                ),
                (
                    "released_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ آزادسازی"
                    ),
                ),
                (
                    "release_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="دلیلِ آزادسازی",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="cart.coupon",
                        verbose_name="کد تخفیف",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coupon_redemptions",
                        to="customers.customer",
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_redemption",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
            ],
            options={
                "verbose_name": "استفاده از کد تخفیف",
                "verbose_name_plural": "استفاده\u200cهای کد تخفیف",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["coupon", "customer", "status"],
                        name="idx_redemption_coupon_cust",
                    )
                ],
            },
        ),
    ]
