# Generated by Django 5.2.17 on 2026-10-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_backfill_order_gift_wrap_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="refunditem",
            name="gift_wrap_amount",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=14,
                verbose_name="مبلغِ کادوپیچیِ استردادشده",
            ),
        ),
    ]
