# Generated by Django 5.2.17 on 2026-10-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_cartitem_gift_message_cartitem_gift_wrap_option_code_and_more"),
        ("catalog", "0039_product_gift_wrap_enabled_product_gift_wrap_price"),
        ("customers", "0004_customer_accepts_promotional_email_and_more"),
        ("orders", "0014_refunditem_gift_wrap_amount"),
        ("stores", "0018_storedomain_delivery_readiness"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["store", "created_at"], name="idx_order_store_created"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["store", "customer", "created_at"],
                name="idx_order_store_cust_created",
            ),
        ),
    ]
