# Generated by Django 5.2.17 on 2026-10-03 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_backfill_coupon_redemptions"),
        ("stores", "0018_storedomain_delivery_readiness"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("order_canceled", "سفارش لغو شده بود"),
                            (
                                "already_paid",
                                "سفارش قبلاً پرداخت شده بود (پرداخت تکراری)",
                            ),
                            ("not_payable", "سفارش در وضعیتِ قابلِ پرداخت نبود"),
                            ("processing_error", "خطا در پردازشِ پرداختِ تأییدشده"),
                        ],
                        max_length=20,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "باز"), ("resolved", "رسیدگی\u200cشده")],
                        db_index=True,
                        default="open",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=14, verbose_name="مبلغِ تأییدشده"
                    ),
                ),
                (
                    "gateway_track_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="شناسه\u200cی پیگیری درگاه",
                    ),
                ),
                (
                    "gateway_ref_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="شماره\u200cی ارجاع بانکی",
                    ),
                ),
                (
                    "order_status_at_detection",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=15,
                        verbose_name="وضعیتِ سفارش در لحظه\u200cی کشف",
                    ),
                ),
                (
                    "payment_status_at_detection",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=15,
                        verbose_name="وضعیتِ پرداختِ سفارش در لحظه\u200cی کشف",
                    ),
                ),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="شواهدِ تأیید درگاه (بدونِ اطلاعاتِ حساس)",
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="خطا (امن)"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ رسیدگی"
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("refunded_outside", "استردادِ خارج از سیستم انجام شد"),
                            ("order_reinstated", "سفارش دستی بازگشایی/جایگزین شد"),
                            ("no_action", "نیازی به اقدام نبود"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="نتیجه\u200cی رسیدگی",
                    ),
                ),
                (
                    "resolution_note",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="یادداشتِ رسیدگی",
                    ),
                ),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliation",
                        to="orders.paymentattempt",
                        verbose_name="تلاش پرداخت",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_reconciliations",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_payment_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="رسیدگی\u200cکننده",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_reconciliations",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "تطبیقِ پرداخت",
                "verbose_name_plural": "تطبیق\u200cهایِ پرداخت",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["store", "status", "-created_at"],
                        name="idx_reconcile_store_status",
                    )
                ],
            },
        ),
    ]
