# Generated by Django 5.2.17 on 2026-10-03 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_payment_reconciliation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="زمانِ تأیید"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تأییدکننده",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="method",
            field=models.CharField(
                choices=[
                    ("gateway", "درگاه پرداخت"),
                    ("cod_cash", "نقدیِ پرداخت در محل"),
                    ("cod_pos", "کارتخوانِ پرداخت در محل"),
                ],
                default="gateway",
                max_length=10,
                verbose_name="روش دریافت",
            ),
        ),
    ]
