# Generated by Django 5.2.17 on 2026-10-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_transaction_cod_confirmation"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentreconciliation",
            name="evidence_level",
            field=models.CharField(
                choices=[
                    ("confirmed", "تأییدشده توسط درگاه"),
                    ("suspected", "مشکوک (تأیید نشده)"),
                ],
                default="confirmed",
                max_length=10,
                verbose_name="سطحِ شواهد",
            ),
        ),
        migrations.AddField(
            model_name="paymentreconciliation",
            name="reported_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=16,
                null=True,
                verbose_name="مبلغِ گزارش\u200cشده توسط درگاه (تومان)",
            ),
        ),
        migrations.AlterField(
            model_name="paymentreconciliation",
            name="amount",
            field=models.DecimalField(
                decimal_places=0,
                max_digits=14,
                verbose_name="مبلغِ مورد انتظار (سفارش/تلاش)",
            ),
        ),
        migrations.AlterField(
            model_name="paymentreconciliation",
            name="kind",
            field=models.CharField(
                choices=[
                    ("order_canceled", "سفارش لغو شده بود"),
                    ("already_paid", "سفارش قبلاً پرداخت شده بود (پرداخت تکراری)"),
                    ("not_payable", "سفارش در وضعیتِ قابلِ پرداخت نبود"),
                    ("processing_error", "خطا در پردازشِ پرداختِ تأییدشده"),
                    ("amount_mismatch", "مبلغِ تأییدشده با سفارش مغایرت دارد"),
                    (
                        "verify_ambiguous",
                        "نتیجه\u200cی تأییدِ درگاه نامشخص (نیازمند بررسی)",
                    ),
                ],
                max_length=20,
                verbose_name="نوع",
            ),
        ),
        migrations.AlterField(
            model_name="paymentreconciliation",
            name="resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("refunded_outside", "استردادِ خارج از سیستم انجام شد"),
                    ("order_reinstated", "سفارش دستی بازگشایی/جایگزین شد"),
                    ("no_action", "نیازی به اقدام نبود"),
                    ("not_paid", "پس از بررسیِ پنلِ درگاه، پرداختی انجام نشده بود"),
                    (
                        "auto_verified",
                        "بعداً توسط درگاه تأیید و به\u200cطور عادی اعمال شد (سیستمی)",
                    ),
                ],
                default="",
                max_length=20,
                verbose_name="نتیجه\u200cی رسیدگی",
            ),
        ),
    ]
