# Generated by Django 5.2.17 on 2026-10-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customersegment_customersegmentrule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="accepts_promotional_email",
            field=models.BooleanField(
                default=True, verbose_name="دریافتِ ایمیلِ تبلیغاتی"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="accepts_promotional_sms",
            field=models.BooleanField(
                default=True, verbose_name="دریافتِ پیامکِ تبلیغاتی"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
        ),
        migrations.AddField(
            model_name="customer",
            name="birth_month_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="ماه/روزِ تولد (جلالی)",
            ),
        ),
    ]
