# Generated by Django 5.2.17 on 2026-10-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customer_accepts_promotional_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customersegmentrule",
            name="operator",
            field=models.CharField(max_length=40, verbose_name="عملگر"),
        ),
    ]
