# Generated by Django 5.2.17 on 2026-10-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_widen_segment_rule_operator"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="promo_email_consent_changed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="زمانِ آخرین تغییرِ رضایتِ ایمیلی"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="promo_email_consent_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("registration", "ثبت\u200cنام"),
                    ("checkout", "تسویه\u200cحساب"),
                    ("account", "تنظیماتِ حسابِ مشتری"),
                    ("admin", "ثبتِ دستیِ مدیر"),
                    ("import", "ورودِ دسته\u200cایِ دارایِ مدرک"),
                    ("legacy_unverified", "قدیمی — بدونِ مدرکِ رضایت (بی\u200cاثر شد)"),
                    ("legacy_opt_out", "قدیمی — انصرافِ صریح"),
                ],
                default="",
                max_length=20,
                verbose_name="منبعِ آخرین تغییرِ رضایتِ ایمیلی",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="promo_sms_consent_changed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="زمانِ آخرین تغییرِ رضایتِ پیامکی"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="promo_sms_consent_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("registration", "ثبت\u200cنام"),
                    ("checkout", "تسویه\u200cحساب"),
                    ("account", "تنظیماتِ حسابِ مشتری"),
                    ("admin", "ثبتِ دستیِ مدیر"),
                    ("import", "ورودِ دسته\u200cایِ دارایِ مدرک"),
                    ("legacy_unverified", "قدیمی — بدونِ مدرکِ رضایت (بی\u200cاثر شد)"),
                    ("legacy_opt_out", "قدیمی — انصرافِ صریح"),
                ],
                default="",
                max_length=20,
                verbose_name="منبعِ آخرین تغییرِ رضایتِ پیامکی",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="accepts_promotional_email",
            field=models.BooleanField(
                default=False, verbose_name="دریافتِ ایمیلِ تبلیغاتی"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="accepts_promotional_sms",
            field=models.BooleanField(
                default=False, verbose_name="دریافتِ پیامکِ تبلیغاتی"
            ),
        ),
    ]
