# Generated by Django 5.2.17 on 2026-09-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront_builder", "0018_r4_editor_gate_and_edit_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="storefrontpage",
            name="page_appearance_overrides",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="بازنویسیِ ظاهرِ صفحه"
            ),
        ),
    ]
