# Generated by Django 5.2.17 on 2026-10-02 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_cartitem_gift_wrap"),
        ("customers", "0004_customer_accepts_promotional_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="gift_message",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="پیامِ کارت\u200cهدیه",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="gift_wrap_option_code",
            field=models.CharField(
                blank=True,
                default="standard",
                help_text="آماده\u200cی افزودنِ گزینه\u200cهایِ متعددِ کادوپیچی با قیمت\u200cهایِ متفاوت در آینده.",
                max_length=30,
                verbose_name="گزینه\u200cی کادوپیچی",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="applies_to_gift_wrap",
            field=models.BooleanField(
                default=False,
                verbose_name="تخفیف روی هزینه\u200cی کادوپیچی هم اعمال شود",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupons",
                to="customers.customer",
                verbose_name="مشتریِ مالک (کد اختصاصی)",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="max_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="سقفِ مبلغِ تخفیف (تومان)",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="max_items",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="حداکثر تعدادِ اقلام"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="max_order",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="حداکثر مبلغِ سبد",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="min_items",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="حداقل تعدادِ اقلام"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="per_customer_limit",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="سقفِ استفاده برای هر مشتری"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="restrictions",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="محدودیت\u200cها"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="stacks_with_product_discount",
            field=models.BooleanField(
                default=True,
                help_text="اگر خاموش باشد، روی اقلامی که تخفیفِ کالا دارند اعمال نمی\u200cشود.",
                verbose_name="قابل\u200cجمع با تخفیفِ خودِ کالا",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="starts_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ فعال\u200cسازی"
            ),
        ),
    ]
