# Generated by Django 5.2.17 on 2026-10-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_cartitem_gift_message_cartitem_gift_wrap_option_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="delivery_anchored_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="زمانِ تحویلِ اعلان (مبدأ اعتبار)"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="per_customer_period_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="پنجره\u200cی سقفِ هر مشتری (روز)"
            ),
        ),
    ]
