# Generated by Django 5.2.17 on 2026-09-28 07:18

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0023_newslettersubscriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroslide",
            name="desktop_image",
            field=models.ImageField(
                blank=True,
                upload_to="homepage/hero/",
                validators=[
                    apps.content.models.validate_image_size,
                    apps.content.models.validate_image_content,
                ],
                verbose_name="تصویر دسکتاپ",
            ),
        ),
        migrations.AlterField(
            model_name="promotionalbanner",
            name="desktop_image",
            field=models.ImageField(
                blank=True,
                upload_to="homepage/banners/",
                validators=[
                    apps.content.models.validate_image_size,
                    apps.content.models.validate_image_content,
                ],
                verbose_name="تصویر دسکتاپ",
            ),
        ),
        migrations.AlterField(
            model_name="storyrailitem",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="storyrail/",
                validators=[
                    apps.content.models.validate_image_size,
                    apps.content.models.validate_image_content,
                ],
                verbose_name="تصویر",
            ),
        ),
    ]
