# Generated by Django 5.2.17 on 2026-10-02 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cart", "0008_cartitem_gift_message_cartitem_gift_wrap_option_code_and_more"),
        ("customers", "0004_customer_accepts_promotional_email_and_more"),
        ("stores", "0018_storedomain_delivery_readiness"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="نام")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="توضیحات"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("active", "فعال"),
                            ("paused", "متوقف"),
                            ("expired", "منقضی\u200cشده"),
                            ("completed", "تکمیل\u200cشده"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "اجرای دستی"),
                            ("scheduled", "زمان\u200cبندی\u200cشده (job دوره\u200cای)"),
                            ("event", "رویداد (پس از پرداختِ موفق)"),
                            ("occasion", "مناسبت"),
                        ],
                        default="manual",
                        max_length=12,
                        verbose_name="نوعِ اجرا",
                    ),
                ),
                (
                    "rules",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="درختِ قواعد"
                    ),
                ),
                (
                    "rule_scope",
                    models.CharField(
                        choices=[
                            (
                                "aggregate",
                                "ترکیبِ سفارش\u200cها (هر شرط می\u200cتواند با سفارشِ متفاوتی برقرار شود)",
                            ),
                            (
                                "same_order",
                                "همه\u200cی شرط\u200cها باید با یک سفارشِ واحد برقرار شوند",
                            ),
                        ],
                        default="aggregate",
                        max_length=12,
                        verbose_name="دامنه\u200cی ارزیابیِ قواعدِ سفارش",
                    ),
                ),
                (
                    "period_mode",
                    models.CharField(
                        choices=[
                            ("none", "بدونِ بازه (کلِ تاریخچه)"),
                            ("jalali_months", "ماه\u200cهای شمسی"),
                            ("dates", "بازه\u200cی تاریخ"),
                        ],
                        default="none",
                        max_length=14,
                        verbose_name="بازه\u200cی خرید",
                    ),
                ),
                (
                    "period_jalali_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="سالِ شمسی"
                    ),
                ),
                (
                    "period_start_month",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="ماهِ شروع (شمسی)"
                    ),
                ),
                (
                    "period_end_month",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="ماهِ پایان (شمسی)"
                    ),
                ),
                (
                    "period_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخِ شروع (میلادی)"
                    ),
                ),
                (
                    "period_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخِ پایان (میلادی)"
                    ),
                ),
                (
                    "valid_payment_statuses",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="وضعیت\u200cهای پرداختِ معتبر",
                    ),
                ),
                (
                    "amount_basis",
                    models.CharField(
                        choices=[
                            ("net_total", "مبلغِ خالص (پس از کسرِ استرداد)"),
                            ("grand_total", "مبلغِ نهایی فاکتور"),
                            ("items_total", "جمعِ کالاها"),
                        ],
                        default="net_total",
                        max_length=12,
                        verbose_name="مبنای مبلغ فاکتور",
                    ),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("coupon", "کدِ تخفیف"),
                            ("none", "فقط اطلاع\u200cرسانی (بدونِ پاداش)"),
                        ],
                        default="coupon",
                        max_length=8,
                        verbose_name="نوع پاداش",
                    ),
                ),
                (
                    "coupon_type",
                    models.CharField(
                        default="percent", max_length=10, verbose_name="نوع تخفیف"
                    ),
                ),
                (
                    "coupon_value",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="مقدار تخفیف",
                    ),
                ),
                (
                    "coupon_max_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="سقفِ مبلغ تخفیف (تومان)",
                    ),
                ),
                (
                    "coupon_min_order",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="حداقل مبلغ سفارش",
                    ),
                ),
                (
                    "coupon_applies_to_gift_wrap",
                    models.BooleanField(
                        default=False, verbose_name="تخفیف روی کادوپیچی هم اعمال شود"
                    ),
                ),
                (
                    "code_prefix",
                    models.CharField(
                        blank=True, default="", max_length=12, verbose_name="پیشوندِ کد"
                    ),
                ),
                (
                    "personalized",
                    models.BooleanField(
                        default=True, verbose_name="کدِ اختصاصیِ هر مشتری"
                    ),
                ),
                (
                    "code_starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="فعال\u200cسازیِ کد"
                    ),
                ),
                (
                    "code_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="انقضایِ کد (تاریخِ ثابت)"
                    ),
                ),
                (
                    "code_valid_days",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="اعتبارِ کد پس از صدور (روز)",
                    ),
                ),
                (
                    "total_redemption_limit",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="سقفِ کلِ استفاده از هر کد"
                    ),
                ),
                (
                    "per_customer_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        default=1,
                        null=True,
                        verbose_name="سقفِ استفاده برایِ هر مشتری",
                    ),
                ),
                (
                    "max_issuances",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="سقفِ تعدادِ کدهایِ صادرشده (ظرفیتِ کمپین)",
                    ),
                ),
                (
                    "channels",
                    models.JSONField(
                        blank=True, default=list, verbose_name="کانال\u200cها"
                    ),
                ),
                (
                    "custom_sms_body",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="متنِ پیامکِ اختصاصیِ کمپین",
                    ),
                ),
                (
                    "custom_email_subject",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="موضوعِ ایمیلِ اختصاصیِ کمپین",
                    ),
                ),
                (
                    "custom_email_body",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="متنِ ایمیلِ اختصاصیِ کمپین",
                    ),
                ),
                (
                    "reminder_days_before_expiry",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="یادآوریِ انقضا (روز مانده)"
                    ),
                ),
                (
                    "occasion_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("birthday", "تولد"),
                            ("registration_anniversary", "سالگردِ ثبت\u200cنام"),
                            ("first_purchase_anniversary", "سالگردِ اولین خرید"),
                            ("order_milestone", "نقطه\u200cی عطفِ تعدادِ سفارش"),
                            ("spending_milestone", "نقطه\u200cی عطفِ مجموعِ خرید"),
                            ("reactivation", "بازگشتِ مشتریِ غیرفعال"),
                            ("holiday", "تعطیلی/مناسبتِ عمومی (ماه/روزِ شمسی)"),
                            ("custom_date", "مناسبتِ اختصاصیِ فروشگاه (تاریخِ مشخص)"),
                        ],
                        default="",
                        max_length=30,
                        verbose_name="نوعِ مناسبت",
                    ),
                ),
                (
                    "occasion_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="نامِ مناسبت (در پیام)",
                    ),
                ),
                (
                    "occasion_offset_days",
                    models.SmallIntegerField(
                        default=0,
                        verbose_name="فاصله\u200cی روز از مناسبت (منفی = پیش از، ۰ = همان روز، مثبت = پس از)",
                    ),
                ),
                (
                    "occasion_params",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="پارامترهایِ مناسبت"
                    ),
                ),
                (
                    "active_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="شروعِ فعالیتِ کمپین"
                    ),
                ),
                (
                    "active_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایانِ فعالیتِ کمپین"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ فعال\u200cسازی"
                    ),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین اجرا"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="سازنده",
                    ),
                ),
                (
                    "shared_coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cart.coupon",
                        verbose_name="کدِ مشترک (کمپینِ غیراختصاصی)",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "کمپین",
                "verbose_name_plural": "کمپین\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignIssuance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "cycle_key",
                    models.CharField(
                        default="once", max_length=60, verbose_name="کلیدِ چرخه"
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ صفِ اعلان"
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issuances",
                        to="engagement.campaign",
                        verbose_name="کمپین",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issuances",
                        to="cart.coupon",
                        verbose_name="کد تخفیف",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_issuances",
                        to="customers.customer",
                        verbose_name="مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "صدورِ پاداش",
                "verbose_name_plural": "صدورهایِ پاداش",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("manual", "دستی"),
                            ("scheduled", "زمان\u200cبندی"),
                            ("event", "رویداد"),
                            ("occasion", "مناسبت"),
                            ("preview", "پیش\u200cنمایش"),
                        ],
                        max_length=10,
                        verbose_name="محرک",
                    ),
                ),
                (
                    "dry_run",
                    models.BooleanField(default=False, verbose_name="خشک (بدونِ صدور)"),
                ),
                ("started_at", models.DateTimeField(verbose_name="شروع")),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="پایان"),
                ),
                (
                    "evaluated",
                    models.PositiveIntegerField(
                        default=0, verbose_name="بررسی\u200cشده"
                    ),
                ),
                (
                    "eligible",
                    models.PositiveIntegerField(default=0, verbose_name="مشمول"),
                ),
                (
                    "issued",
                    models.PositiveIntegerField(default=0, verbose_name="صادرشده"),
                ),
                (
                    "skipped_existing",
                    models.PositiveIntegerField(
                        default=0, verbose_name="قبلاً صادرشده"
                    ),
                ),
                ("errors", models.PositiveIntegerField(default=0, verbose_name="خطا")),
                (
                    "error_text",
                    models.TextField(blank=True, default="", verbose_name="متنِ خطا"),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="engagement.campaign",
                        verbose_name="کمپین",
                    ),
                ),
            ],
            options={
                "verbose_name": "اجرای کمپین",
                "verbose_name_plural": "اجراهایِ کمپین",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["store", "status", "trigger_type"],
                name="idx_campaign_store_status",
            ),
        ),
        migrations.AddIndex(
            model_name="campaignissuance",
            index=models.Index(
                fields=["customer", "campaign"], name="idx_issuance_customer"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignissuance",
            constraint=models.UniqueConstraint(
                fields=("campaign", "customer", "cycle_key"),
                name="uniq_campaign_issuance_cycle",
            ),
        ),
    ]
