# Generated by Django 5.2.17 on 2026-10-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="per_customer_period_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="پنجره\u200cی سقفِ هر مشتری (روز)"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="validity_from_delivery",
            field=models.BooleanField(
                default=False,
                verbose_name="اعتبارِ کد از لحظه\u200cی تحویلِ اعلان حساب شود (نه صدور)",
            ),
        ),
    ]
