# Generated by Django 5.2.17 on 2026-10-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0002_period_limit_delivery_validity"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="channels_explicit",
            field=models.BooleanField(
                default=False,
                help_text="خاموش (کمپین\u200cهایِ قدیمی): فهرستِ خالیِ کانال\u200cها یعنی «همه\u200cی کانال\u200cهایِ فعال». روشن: فهرست دقیقاً همان است و خالی یعنی هیچ پیامی ارسال نشود.",
                verbose_name="کانال\u200cها صریحاً انتخاب شده\u200cاند",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="custom_sms_body",
            field=models.TextField(
                blank=True,
                default="",
                help_text="دیگر هرگز ارسال نمی\u200cشود: متنِ پیامکِ کمپین/مناسبت فقط از قالبِ پلتفرم می\u200cآید.",
                verbose_name="متنِ پیامکِ اختصاصیِ کمپین (منسوخ)",
            ),
        ),
    ]
