# Generated by Django 5.2.17 on 2026-10-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_shopsettings_gift_wrap"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="gift_wrap_description",
            field=models.CharField(
                blank=True,
                default="",
                max_length=300,
                verbose_name="توضیحِ سرویسِ کادوپیچی",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="gift_wrap_image",
            field=models.ImageField(
                blank=True,
                upload_to="shop/gift_wrap/",
                verbose_name="تصویرِ نمونه\u200cی کادوپیچی",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="gift_wrap_message_enabled",
            field=models.BooleanField(
                default=True, verbose_name="امکانِ نوشتنِ پیامِ کارت\u200cهدیه"
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="gift_wrap_pricing_scope",
            field=models.CharField(
                choices=[
                    ("per_unit", "به\u200cازای هر عددِ کالا"),
                    ("per_line", "به\u200cازای هر ردیفِ سبد"),
                    ("per_order", "یک\u200cبار برای کلِ سفارش"),
                ],
                default="per_unit",
                max_length=10,
                verbose_name="مبنای محاسبه\u200cی هزینه\u200cی کادوپیچی",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="gift_wrap_title",
            field=models.CharField(
                default="کادوپیچی", max_length=80, verbose_name="عنوان سرویسِ کادوپیچی"
            ),
        ),
        migrations.AlterField(
            model_name="shopsettings",
            name="gift_wrap_price",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="هزینه\u200cی کادوپیچی (تومان؛ ۰ = رایگان)",
            ),
        ),
    ]
