# Generated by Django 5.2.17 on 2026-10-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_shopsettings_gift_wrap_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="unpaid_expiry_notify_sms",
            field=models.BooleanField(
                default=False, verbose_name="ارسالِ پیامکِ لغو هنگامِ انقضا"
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="unpaid_online_order_grace_minutes",
            field=models.PositiveIntegerField(
                default=30,
                help_text="سفارشی که تلاشِ پرداختِ بازی با فعالیتِ کمتر از این مدت دارد منقضی نمی\u200cشود.",
                verbose_name="مهلتِ تکمیلی برایِ پرداختِ در حال انجام (دقیقه)",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="unpaid_online_order_ttl_minutes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="سفارشِ در انتظارِ پرداختِ آنلاین پس از این مدت لغو می\u200cشود (موجودی و ظرفیتِ کدِ تخفیف برمی\u200cگردد). ۰ یعنی هرگز. مقدارِ پیشنهادی ۶۰ — باید از طولِ عمرِ نشستِ درگاه بیشتر باشد.",
                verbose_name="مهلتِ پرداختِ سفارشِ آنلاین (دقیقه؛ ۰ = غیرفعال)",
            ),
        ),
    ]
