# Generated by Django 5.2.17 on 2026-10-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_unpaid_order_expiry_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="smsrasti_last_seen_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="آخرین اتصالِ دستگاهِ اسمس\u200cراستی",
            ),
        ),
    ]
