# Generated by Django 5.2.17 on 2026-10-06 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_smsrasti_last_seen"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exportjob",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "درخواستِ خروجِ اطلاعات",
                "verbose_name_plural": "درخواست\u200cهایِ خروجِ اطلاعات",
            },
        ),
        migrations.AlterModelOptions(
            name="importjob",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "درخواستِ ورودِ اطلاعات",
                "verbose_name_plural": "درخواست\u200cهایِ ورودِ اطلاعات",
            },
        ),
        migrations.AlterModelOptions(
            name="importrowresult",
            options={
                "ordering": ["import_job_id", "row_number"],
                "verbose_name": "نتیجه\u200cی ردیفِ ورودِ اطلاعات",
                "verbose_name_plural": "نتایجِ ردیف\u200cهایِ ورودِ اطلاعات",
            },
        ),
        migrations.AlterField(
            model_name="exportjob",
            name="export_type",
            field=models.CharField(
                choices=[
                    ("products", "کالاها"),
                    ("variants", "تنوع\u200cها"),
                    ("inventory", "موجودیِ انبار"),
                    ("customers", "مشتریان"),
                    ("orders", "سفارش\u200cها"),
                ],
                max_length=20,
                verbose_name="نوعِ خروجِ اطلاعات",
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="import_type",
            field=models.CharField(
                choices=[
                    ("products", "کالاها"),
                    ("variants", "تنوع\u200cها"),
                    ("inventory", "موجودیِ انبار"),
                ],
                max_length=20,
                verbose_name="نوعِ اطلاعاتِ ورودی",
            ),
        ),
        migrations.AlterField(
            model_name="importrowresult",
            name="import_job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="row_results",
                to="core.importjob",
                verbose_name="درخواستِ ورودِ اطلاعات",
            ),
        ),
    ]
