# Generated by Django 5.2.18 on 2026-10-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0010_publicsitephoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownerotpchallenge",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("register", "ثبت\u200cنام"),
                    ("login", "ورود"),
                    ("step_up", "تأییدِ عملیاتِ حساس (Section 10)"),
                    ("reset", "بازیابی رمز عبور"),
                ],
                max_length=10,
                verbose_name="هدف",
            ),
        ),
    ]
