# Generated by Django 5.2.18 on 2026-10-08 09:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0011_owner_otp_purpose_password_reset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerTermsAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "terms_version",
                    models.CharField(max_length=40, verbose_name="نسخه\u200cی قوانین"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="زمانِ پذیرش"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("registration", "ثبت\u200cنام (/register/)"),
                            ("signup_complete", "تکمیل ثبت\u200cنام پس از ورودِ OTP"),
                        ],
                        max_length=20,
                        verbose_name="مسیرِ پذیرش",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms_acceptances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "پذیرشِ قوانین توسطِ مالک",
                "verbose_name_plural": "پذیرش\u200cهایِ قوانین توسطِ مالکان",
                "indexes": [
                    models.Index(
                        fields=["terms_version"], name="idx_owner_terms_version"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "terms_version"),
                        name="uniq_owner_terms_acceptance_user_version",
                    )
                ],
            },
        ),
    ]
