# Generated by Django 5.2.17 on 2026-10-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0008_sms_control_center"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smslog",
            name="event_key",
            field=models.CharField(
                choices=[
                    ("platform_owner_otp", "OTP ثبت\u200cنام / ورود مالک فروشگاه"),
                    ("platform_test", "تست زیرساخت پیامک"),
                    ("notification", "اعلان عمومی / امنیتی"),
                    ("welcome", "ثبت\u200cنام / خوش\u200cآمدگویی"),
                    ("otp", "کد ورود یکبار مصرف"),
                    ("order_placed", "ثبت سفارش"),
                    ("payment_success", "پرداخت موفق"),
                    ("payment_failed", "پرداخت ناموفق"),
                    ("order_processing", "سفارش در حال پردازش"),
                    ("order_shipped", "ارسال سفارش"),
                    ("order_delivered", "تحویل سفارش"),
                    ("order_canceled", "لغو سفارش"),
                    (
                        "occ_birthday_before",
                        "مناسبت · تولد · پیش از روز تولد (با هدیه)",
                    ),
                    ("occ_birthday_on", "مناسبت · تولد · روز تولد (با هدیه)"),
                    ("occ_birthday_after", "مناسبت · تولد · پس از روز تولد (با هدیه)"),
                    (
                        "occ_birthday_before_nogift",
                        "مناسبت · تولد · پیش از روز تولد (فقط تبریک)",
                    ),
                    ("occ_birthday_on_nogift", "مناسبت · تولد · روز تولد (فقط تبریک)"),
                    (
                        "occ_birthday_after_nogift",
                        "مناسبت · تولد · پس از روز تولد (فقط تبریک)",
                    ),
                    (
                        "occ_generic_before",
                        "مناسبت · سایر مناسبت\u200cها · پیش از مناسبت (با هدیه)",
                    ),
                    (
                        "occ_generic_on",
                        "مناسبت · سایر مناسبت\u200cها · روز مناسبت (با هدیه)",
                    ),
                    (
                        "occ_generic_after",
                        "مناسبت · سایر مناسبت\u200cها · پس از مناسبت (با هدیه)",
                    ),
                    (
                        "occ_generic_before_nogift",
                        "مناسبت · سایر مناسبت\u200cها · پیش از مناسبت (فقط تبریک)",
                    ),
                    (
                        "occ_generic_on_nogift",
                        "مناسبت · سایر مناسبت\u200cها · روز مناسبت (فقط تبریک)",
                    ),
                    (
                        "occ_generic_after_nogift",
                        "مناسبت · سایر مناسبت\u200cها · پس از مناسبت (فقط تبریک)",
                    ),
                    ("camp_offer_percent", "کمپین تخفیف · تخفیف درصدی"),
                    ("camp_offer_fixed", "کمپین تخفیف · تخفیف مبلغی"),
                    ("camp_offer_free_ship", "کمپین تخفیف · ارسال رایگان"),
                    ("camp_announce", "کمپین تخفیف · اطلاع\u200cرسانی بدون کد"),
                    (
                        "camp_expiry_reminder",
                        "کمپین/مناسبت · یادآوری نزدیک\u200cشدن انقضای کد",
                    ),
                ],
                max_length=30,
                verbose_name="رویداد",
            ),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="event_key",
            field=models.CharField(
                choices=[
                    ("platform_owner_otp", "OTP ثبت\u200cنام / ورود مالک فروشگاه"),
                    ("platform_test", "تست زیرساخت پیامک"),
                    ("notification", "اعلان عمومی / امنیتی"),
                    ("welcome", "ثبت\u200cنام / خوش\u200cآمدگویی"),
                    ("otp", "کد ورود یکبار مصرف"),
                    ("order_placed", "ثبت سفارش"),
                    ("payment_success", "پرداخت موفق"),
                    ("payment_failed", "پرداخت ناموفق"),
                    ("order_processing", "سفارش در حال پردازش"),
                    ("order_shipped", "ارسال سفارش"),
                    ("order_delivered", "تحویل سفارش"),
                    ("order_canceled", "لغو سفارش"),
                    (
                        "occ_birthday_before",
                        "مناسبت · تولد · پیش از روز تولد (با هدیه)",
                    ),
                    ("occ_birthday_on", "مناسبت · تولد · روز تولد (با هدیه)"),
                    ("occ_birthday_after", "مناسبت · تولد · پس از روز تولد (با هدیه)"),
                    (
                        "occ_birthday_before_nogift",
                        "مناسبت · تولد · پیش از روز تولد (فقط تبریک)",
                    ),
                    ("occ_birthday_on_nogift", "مناسبت · تولد · روز تولد (فقط تبریک)"),
                    (
                        "occ_birthday_after_nogift",
                        "مناسبت · تولد · پس از روز تولد (فقط تبریک)",
                    ),
                    (
                        "occ_generic_before",
                        "مناسبت · سایر مناسبت\u200cها · پیش از مناسبت (با هدیه)",
                    ),
                    (
                        "occ_generic_on",
                        "مناسبت · سایر مناسبت\u200cها · روز مناسبت (با هدیه)",
                    ),
                    (
                        "occ_generic_after",
                        "مناسبت · سایر مناسبت\u200cها · پس از مناسبت (با هدیه)",
                    ),
                    (
                        "occ_generic_before_nogift",
                        "مناسبت · سایر مناسبت\u200cها · پیش از مناسبت (فقط تبریک)",
                    ),
                    (
                        "occ_generic_on_nogift",
                        "مناسبت · سایر مناسبت\u200cها · روز مناسبت (فقط تبریک)",
                    ),
                    (
                        "occ_generic_after_nogift",
                        "مناسبت · سایر مناسبت\u200cها · پس از مناسبت (فقط تبریک)",
                    ),
                    ("camp_offer_percent", "کمپین تخفیف · تخفیف درصدی"),
                    ("camp_offer_fixed", "کمپین تخفیف · تخفیف مبلغی"),
                    ("camp_offer_free_ship", "کمپین تخفیف · ارسال رایگان"),
                    ("camp_announce", "کمپین تخفیف · اطلاع\u200cرسانی بدون کد"),
                    (
                        "camp_expiry_reminder",
                        "کمپین/مناسبت · یادآوری نزدیک\u200cشدن انقضای کد",
                    ),
                ],
                max_length=30,
                unique=True,
                verbose_name="رویداد",
            ),
        ),
    ]
