# Generated by Django 5.2.18 on 2026-10-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0019_store_onboarding_stage_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="onboarding_required_at",
            field=models.DateTimeField(
                blank=True,
                help_text="نشانهٔ پایدارِ «این فروشگاه از مسیرِ مدرنِ ثبت\u200cنام/ساخت در پورتال ساخته شده و باید پیش از عمومی\u200cشدن، آنبوردینگ را با «انتشار» تمام کند». فقط ``provisioning_service.provision_trial_store`` آن را هنگامِ ساخت مقداردهی می\u200cکند؛ فروشگاه\u200cهایِ قدیمی/ساخته\u200cشده به\u200cصورتِ دستی NULL می\u200cمانند و رفتارِ fail-open (ADR-65) آن\u200cها دست\u200cنخورده است. تا وقتی این مقدار هست و ``onboarding_completed_at`` خالی است، ``publication_service`` فروشگاه را غیرعمومی می\u200cداند — صرف\u200cنظر از وجود یا نبودِ اشتراک.",
                null=True,
                verbose_name="زمان الزامِ راه\u200cاندازیِ اولیه",
            ),
        ),
    ]
