# Generated by Django 5.2.17 on 2026-10-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0038_productmetafield"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gift_wrap_enabled",
            field=models.BooleanField(
                default=True, verbose_name="امکانِ کادوپیچیِ این کالا"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="gift_wrap_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="خالی = استفاده از قیمتِ عمومیِ فروشگاه؛ ۰ = رایگان.",
                max_digits=12,
                null=True,
                verbose_name="هزینه\u200cی کادوپیچیِ اختصاصیِ این کالا (تومان)",
            ),
        ),
    ]
