# Generated by Django 5.2.17 on 2026-10-02 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customer_accepts_promotional_email_and_more"),
        ("notifications", "0001_initial"),
        ("orders", "0014_refunditem_gift_wrap_amount"),
        ("stores", "0018_storedomain_delivery_readiness"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("event_key", models.CharField(max_length=60, verbose_name="رویداد")),
                (
                    "channel",
                    models.CharField(
                        choices=[("sms", "پیامک"), ("email", "ایمیل")],
                        max_length=10,
                        verbose_name="کانال",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="موضوعِ ایمیل",
                    ),
                ),
                ("body", models.TextField(verbose_name="متن")),
                (
                    "extra_recipients",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="برایِ رویدادهایِ کارکنان: هر خط یک ایمیل/شماره موبایل.",
                        verbose_name="گیرندگانِ اضافی (کارکنان)",
                    ),
                ),
            ],
            options={
                "verbose_name": "قالبِ اعلان",
                "verbose_name_plural": "قالب\u200cهایِ اعلان",
                "ordering": ["event_key", "channel"],
            },
        ),
        migrations.AddField(
            model_name="notificationoutbox",
            name="claimed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="زمانِ برداشتِ کارگر"
            ),
        ),
        migrations.AddField(
            model_name="notificationoutbox",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="customers.customer",
                verbose_name="مشتری",
            ),
        ),
        migrations.AddField(
            model_name="notificationoutbox",
            name="dedupe_key",
            field=models.CharField(
                blank=True,
                default="",
                max_length=220,
                verbose_name="کلیدِ جلوگیری از تکرار",
            ),
        ),
        migrations.AddField(
            model_name="notificationoutbox",
            name="event_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=60,
                verbose_name="رویداد",
            ),
        ),
        migrations.AddField(
            model_name="notificationoutbox",
            name="is_promotional",
            field=models.BooleanField(default=False, verbose_name="تبلیغاتی"),
        ),
        migrations.AddField(
            model_name="notificationoutbox",
            name="is_test",
            field=models.BooleanField(default=False, verbose_name="ارسالِ آزمایشی"),
        ),
        migrations.AddField(
            model_name="notificationoutbox",
            name="max_attempts",
            field=models.PositiveSmallIntegerField(default=5, verbose_name="سقفِ تلاش"),
        ),
        migrations.AddField(
            model_name="notificationoutbox",
            name="next_attempt_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="زمانِ تلاشِ بعدی"
            ),
        ),
        migrations.AddField(
            model_name="notificationoutbox",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="orders.order",
                verbose_name="سفارش",
            ),
        ),
        migrations.AddField(
            model_name="notificationoutbox",
            name="provider",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="ارائه\u200cدهنده"
            ),
        ),
        migrations.AddField(
            model_name="notificationoutbox",
            name="provider_ref",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="شناسه\u200cی ارجاعِ ارائه\u200cدهنده",
            ),
        ),
        migrations.AddField(
            model_name="notificationoutbox",
            name="skip_reason",
            field=models.CharField(
                blank=True,
                default="",
                max_length=120,
                verbose_name="دلیلِ ارسال\u200cنشدن",
            ),
        ),
        migrations.AlterField(
            model_name="notificationoutbox",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظارِ ارسال"),
                    ("sending", "در حالِ ارسال"),
                    ("sent", "ارسال\u200cشده"),
                    ("failed", "ناموفق (قابلِ تلاشِ دوباره)"),
                    ("dead", "ناموفقِ نهایی"),
                    ("skipped", "ارسال\u200cنشده (رضایت/گیرنده/متغیر)"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationoutbox",
            index=models.Index(
                fields=["store", "event_key", "-created_at"],
                name="idx_notif_store_event",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationoutbox",
            index=models.Index(
                fields=["status", "next_attempt_at"], name="idx_notif_status_next"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationoutbox",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dedupe_key", ""), _negated=True),
                fields=("dedupe_key",),
                name="uniq_notification_dedupe_key",
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_templates",
                to="stores.store",
                verbose_name="فروشگاه",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationtemplate",
            constraint=models.UniqueConstraint(
                fields=("store", "event_key", "channel"),
                name="uniq_notification_template",
            ),
        ),
    ]
