# Generated by Django 5.2.17 on 2026-10-02 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_event_outbox_and_templates"),
        ("sms", "0008_sms_control_center"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationoutbox",
            name="sms_log",
            field=models.OneToOneField(
                blank=True,
                help_text="ردیف\u200cهایِ آینه\u200cایِ پیامکِ قدیمی (apps.sms): فقط تاریخچه\u200cاند و هرگز توسطِ کارگرِ ارسال برداشته نمی\u200cشوند.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_mirror",
                to="sms.smslog",
                verbose_name="گزارشِ پیامکِ قدیمی",
            ),
        ),
    ]
